In [3]:
import tensorflow as tf

C:\Users\Yun\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
# Data set
x_data = [[73.,80., 75.],[93., 88., 93.], [89., 91., 90.],
         [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [5]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X,W) + b

In [6]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [10]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "cost = ", cost_val, "\nhypothesis =\n", hy_val)

0 cost =  9668.632 
hypothesis =
 [[65.03356 ]
 [78.93777 ]
 [77.19977 ]
 [86.98361 ]
 [57.867134]]
100 cost =  6.088601 
hypothesis =
 [[152.19325]
 [183.8108 ]
 [180.4746 ]
 [199.44489]
 [137.88916]]
200 cost =  5.9352098 
hypothesis =
 [[152.13524]
 [183.85146]
 [180.45793]
 [199.42416]
 [137.94981]]
300 cost =  5.7891517 
hypothesis =
 [[152.07886]
 [183.89096]
 [180.44176]
 [199.40384]
 [138.00897]]
400 cost =  5.6499963 
hypothesis =
 [[152.0241 ]
 [183.9294 ]
 [180.4261 ]
 [199.38388]
 [138.06668]]
500 cost =  5.51744 
hypothesis =
 [[151.9709 ]
 [183.96675]
 [180.41092]
 [199.3643 ]
 [138.12297]]
600 cost =  5.3911366 
hypothesis =
 [[151.91919]
 [184.00302]
 [180.39615]
 [199.34503]
 [138.17783]]
700 cost =  5.270719 
hypothesis =
 [[151.86897]
 [184.03833]
 [180.38187]
 [199.32614]
 [138.23137]]
800 cost =  5.1559095 
hypothesis =
 [[151.82022]
 [184.07263]
 [180.36804]
 [199.30759]
 [138.2836 ]]
900 cost =  5.0464454 
hypothesis =
 [[151.77283]
 [184.10597]
 [180.35461]
 [19