In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

/home/banana/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
filename_queue = tf.train.string_input_producer(
    ['./Data/data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [3]:
# Default values, in case of empty columns. Also specified the type of the
# Decoded result
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [4]:
# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

In [5]:
# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [6]:
# Hypothesis
hypothesis = tf.matmul(X,W)+ b
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [7]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [8]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [9]:
# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

In [11]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_bal, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X:x_batch, Y:y_batch})
    if step % 200 == 0:
        print(step, "Cost =", cost_val, "\nPrediction\n", hy_bal)
        
coord.request_stop()
coord.join(threads)

0 Cost = 5.068313 
Prediction
 [[143.81348]
 [142.34375]
 [186.70724]
 [153.6984 ]
 [151.129  ]
 [188.37973]
 [145.21925]
 [180.98343]
 [177.76506]
 [159.16788]]
200 Cost = 5.0490837 
Prediction
 [[143.82059]
 [142.37614]
 [186.6643 ]
 [153.63585]
 [151.15433]
 [188.39603]
 [145.14697]
 [181.00778]
 [177.71472]
 [159.12225]]
400 Cost = 5.034847 
Prediction
 [[143.82713]
 [142.4055 ]
 [186.62497]
 [153.57841]
 [151.1778 ]
 [188.41066]
 [145.0803 ]
 [181.03078]
 [177.66872]
 [159.08066]]
600 Cost = 5.0247407 
Prediction
 [[143.83325]
 [142.43213]
 [186.58896]
 [153.52571]
 [151.19958]
 [188.42383]
 [145.0188 ]
 [181.05258]
 [177.62675]
 [159.0428 ]]
800 Cost = 5.0179496 
Prediction
 [[143.83893]
 [142.45628]
 [186.55598]
 [153.47731]
 [151.21983]
 [188.43567]
 [144.96208]
 [181.07321]
 [177.58842]
 [159.00832]]
1000 Cost = 5.0137987 
Prediction
 [[143.8442 ]
 [142.47813]
 [186.52577]
 [153.43285]
 [151.2386 ]
 [188.4463 ]
 [144.90968]
 [181.09276]
 [177.55342]
 [158.97693]]
1200 Cost = 5