In [6]:
import tensorflow as tf

C:\Users\Yun\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [1]:
# Data set
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [7]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [8]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - y))
# Minimize Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [10]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, y:y_data})
    if step % 100 == 0:
        print(step, "cost = ", cost_val, "\nhypothesis =\n", hy_val)

0 cost =  3847.6118 
hypothesis =
 [204.96532 252.09868 245.81715 263.80103 196.78708]
100 cost =  6.6539717 
hypothesis =
 [150.05132 185.95337 180.7167  192.90778 146.29977]
200 cost =  6.4323225 
hypothesis =
 [150.12442 185.9025  180.73814 192.9308  146.22664]
300 cost =  6.221816 
hypothesis =
 [150.19548 185.85301 180.75896 192.95337 146.15538]
400 cost =  6.021821 
hypothesis =
 [150.26457 185.80489 180.77914 192.97548 146.08592]
500 cost =  5.831794 
hypothesis =
 [150.33177 185.7581  180.79878 192.99715 146.01822]
600 cost =  5.651223 
hypothesis =
 [150.39703 185.7126  180.81783 193.01839 145.95221]
700 cost =  5.4796157 
hypothesis =
 [150.46048 185.66833 180.83629 193.03918 145.88786]
800 cost =  5.316514 
hypothesis =
 [150.52217 185.62534 180.85425 193.05959 145.82515]
900 cost =  5.161393 
hypothesis =
 [150.58209 185.58345 180.87161 193.07956 145.76396]
1000 cost =  5.014005 
hypothesis =
 [150.6404  185.5428  180.88855 193.09917 145.70439]
1100 cost =  4.8737397 
hypot